version: '3.7'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - "8080:80"
        links:
            - php-fpm
    php-fpm:
        build:
          context: ./
          dockerfile: docker/php-fpm.docker
        volumes:
        - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/storage/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=dbuser"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=database"
        ports:
            - "33061:3306"